# frozen_string_literal: true

module Gotsha
  class ActionDispatcher
    INIT_SETUP_ACTION = "init"
    DEFAULT_ACTION = "run"

    def self.call(action_name = DEFAULT_ACTION)
      if Config::USER_CONFIG.none? && action_name != INIT_SETUP_ACTION
        raise Errors::HardFail, "config files not found, please run `bundle exec gotsha init` first"
      end

      if Config::USER_CONFIG.key?("autogenerated")
        raise Errors::HardFail,
              "autogenerated config detected! Please, remove `autogenerated: true` from `.gotsha/config.yml`"
      end

      action_name ||= DEFAULT_ACTION

      begin
        action = const_get("Gotsha::Actions::#{action_name.capitalize}")
      rescue NameError
        raise Errors::HardFail,
              "unknown command `#{action_name}`, avaible commands: \n\n#{Gotsha::Actions.constants.map(&:downcase).join("\n")}"
      end

      action.new.call
    end
  end
end
