# frozen_string_literal: true

require "fileutils"
require "yaml"
require_relative "actions/init"
require_relative "actions/run"
require_relative "actions/verify"
require_relative "bash_command"
require_relative "config"

module Gotsha
  class ActionDispatcher
    DEFAULT_ACTION = "run"

    def self.call(action_name = DEFAULT_ACTION)
      if Config::USER_CONFIG.key?("autogenerated")
        raise Errors::ActionFailed,
              "autogenerated config detected! Please, remove `autogenerated: true` from `.gotsha/config.yml`"
      end

      action_name ||= DEFAULT_ACTION

      begin
        action = const_get("Gotsha::Actions::#{action_name.capitalize}")
      rescue NameError
        raise Errors::ActionFailed, "unknown command `#{action_name}`"
      end

      action.new.call
    end
  end
end
