# frozen_string_literal: true

module Gotsha
  module Errors
    class NoCommandConfigured < StandardError; end
    class AutogeneratedConfigDetected < StandardError; end
    class ActionFailed < StandardError; end
  end
end
