# frozen_string_literal: true

module Gotsha
  module Actions
    class Run
      def call
        config = YAML.load_file(Config::CONFIG_FILE)

        if config.key?("autogenerated")
          raise Errors::ActionFailed,
                "autogenerated config detected! Please, remove `autogenerated: true` from .gotsha/config.yml"
        end

        commands = Array(config.fetch("commands")).join(" && ")

        if commands.empty?
          raise(Errors::ActionFailed,
                "please, define some test commands in `.gotsha/config.yml`")
        end

        raise(Errors::ActionFailed, "tests failed") unless Kernel.system(commands)

        Kernel.system("git notes --ref=gotsha add -f -m 'ok'")

        "tests passed"
      rescue Errno::ENOENT
        raise Errors::ActionFailed, "config files not found, please run `bundle exec gotsha init` first"
      end
    end
  end
end
