# frozen_string_literal: true

module Gotsha
  module Actions
    class Run
      def call
        config = YAML.load_file(Config::CONFIG_FILE)

        if config.key?("autogenerated")
          raise Errors::ActionFailed,
                "autogenerated config detected! Please, remove `autogenerated: true` from .gotsha/config.yml"
        end

        commands = Array(config.fetch("commands")).join(" && ")

        raise(Errors::ActionFailed, "you need to define some test commands to run in `.gotsha/config.yml`") if commands.to_s.empty?

        raise(Errors::ActionFailed, "tests failed") unless Kernel.system(commands)

        Kernel.system("git notes --ref=gotsha add -f -m 'ok'")

        "tests passed"
      rescue Errno::ENOENT
        raise Errors::ActionFailed, "config files not found, please run `bundle exec gotsha init` first"
      end
    end
  end
end
