# frozen_string_literal: true

module Gotsha
  module Actions
    class Run
      def call
        config = YAML.load_file(Config::CONFIG_FILE)

        if config.key?("autogenerated")
          raise Errors::AutogeneratedConfigDetected,
                "Autogenerated config detected! Please, remove `autogenerated: true` from .gotsha/config.yml"
        end

        commands = config.fetch("commands").join(" && ")

        raise Errors::NoCommandConfigured if commands.to_s.empty?

        raise(Errors::ActionFailed, "tests failed") unless Kernel.system(commands)

        Kernel.system("git notes --ref=gotsha add -f -m 'ok'")

        "tests passed"
      end
    end
  end
end
