#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/gotsha"

action = ARGV.first

begin
  message = Gotsha::ActionDispatcher.call(action)
  puts("\n✓ Gotsha: #{message}\n\n")
  exit 0
rescue Gotsha::Errors::SoftFail => e
  puts "\n✗ Gotsha: #{e.message}\n\n"
  exit 0
rescue Gotsha::Errors::HardFail => e
  puts "\n✗ Gotsha: #{e.message}\n\n"
  exit 1
end
