#!/usr/bin/env bash
set -euo pipefail

[ -f .gotsha/config.yml ] || exit 0

grep -qE 'pre_push_tests:\s*true' .gotsha/config.yml && (bundle exec gotsha verify || bundle exec gotsha)
git push --no-verify origin refs/notes/gotsha:refs/notes/gotsha && return 0

git fetch origin 'refs/notes/gotsha:refs/notes/gotsha-remote'
git notes --ref=gotsha merge -v refs/notes/gotsha-remote
git update-ref -d refs/notes/gotsha-remote
git push --no-verify origin refs/notes/gotsha:refs/notes/gotsha
