#!/usr/bin/env bash
set -euo pipefail

[ -f .gotsha/config.yml ] || exit 0

grep -qE 'pre_push_tests:\s*true' .gotsha/config.yml && (bundle exec gotsha verify || bundle exec gotsha)
git push --no-verify origin refs/notes/gotsha:refs/notes/gotsha # TODO: hide the output

