#!/usr/bin/env bash
set -euo pipefail

[ -f .gotsha/config.yml ] || exit 0

grep -qE 'pre_push_tests:\s*true' .gotsha/config.yml && (exe/gotsha verify || exe/gotsha)

push_gotsha_notes() {
  # if already done before, let's only push the notes and exit
  git push --no-verify origin refs/notes/gotsha:refs/notes/gotsha && return 0

  # if pushing above failed, it means we need to do some one-time Git setup
  git fetch origin 'refs/notes/gotsha:refs/notes/gotsha-remote'
  git notes --ref=gotsha merge -v refs/notes/gotsha-remote
  git update-ref -d refs/notes/gotsha-remote

  # ... and push again!
  git push --no-verify origin refs/notes/gotsha:refs/notes/gotsha
}

push_gotsha_notes
